[package]
name = "picturama"
version = "2.0.0"
edition = "2021"

[[bin]]
name = "Picturama"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
chrono             = "0.4"
dirs               = "5"
log                = "0.4"
once_cell          = "1"
open               = "5"
rusqlite           = { version = "0.31", features = ["bundled"] }
serde              = { version = "1.0", features = ["derive"] }
serde_json         = "1"
serde_yaml         = "0.9"
sys-locale         = "0.3"
tauri              = { version = "2", features = ["protocol-asset"] }
tauri-plugin-log   = "2"
tauri-plugin-shell = "2"
tokio              = { version = "1", features = ["full"] }
trash              = "3"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
